apiVersion: batch/v1
kind: CronJob
metadata:
  name: dyndns
spec:
  schedule: "*/5 * * * *" # every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dyndns
            image: dyndns:latest
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/dyndns-key.json
            volumeMounts:
            - name: dyndns-key
              mountPath: /secrets
              readOnly: true
          restartPolicy: OnFailure
          volumes:
          - name: dyndns-key
            secret:
              secretName: gcp-dns-key
