# /etc/rancher/k3s/manifests/registry.yaml
apiVersion: v1
kind: Pod
metadata:
  name: local-registry
  namespace: kube-system
spec:
  hostNetwork: true   # optional: binds directly to host ports
  containers:
  - name: dump-registry
    image: registry:2
    ports:
      - containerPort: 5000
        hostPort: 5000
    volumeMounts:
      - name: registry-data
        mountPath: /var/lib/registry
  volumes:
    - name: registry-data
      hostPath:
        path: /opt/registry/data
        type: DirectoryOrCreate 
